name: Build and release

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
    - name: Build and generate artifact
      run: ./tools/release-deploy.sh
    - name: Preelease
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: ./release/ED64P.zip

